---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.5.1 # 11.18.12

provisioner:
  name: chef_zero
  attributes:
    apt:
      compile_time_update: true
    varnish:
      backend_host: '127.0.0.10'

platforms:
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: centos-7.2
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
- name: centos-6.8
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]

suites:
- name: varnish3
  excludes:
    - centos-7.2
  run_list:
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 3.0
- name: varnish4
  run_list:
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 4.0
- name: varnish41
  run_list:
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 4.1
- name: distro
  run_list:
    - recipe[install_varnish::distro_install]
- name: full_stack
  run_list:
    - recipe[install_varnish::full_stack]
